name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - conda=22.11.1
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=38.0.4
  - fmt=9.1.0
  - icu=70.1
  - idna=3.4
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.39
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libmamba=1.0.0
  - libmambapy=1.0.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsolv=0.7.22
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=1.0.0
  - ncurses=6.3
  - numpy=1.23.5
  - openssl=3.0.7
  - pip=22.3.1
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=22.1.0
  - pysocks=1.7.1
  - python=3.9.10
  - python_abi=3.9
  - readline=8.1.2
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.28.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - ruamel_yaml=0.15.80
  - setuptools=65.5.1
  - sqlite=3.40.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.64.1
  - tzdata=2022f
  - urllib3=1.26.11
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zstandard=0.19.0
  - zstd=1.5.2
